
FROM node:16.13.2-alpine3.15

WORKDIR /usr/src/api

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

ARG mongo_url

ARG server_port=4000

ENV MONGO_URL=${mongo_url}

ENV SERVER_PORT=${server_port}

RUN yarn build

EXPOSE ${server_port}

CMD yarn start